doctrine_migrations:
    dir_name: '%kernel.project_dir%/build/Migration'
    # namespace is arbitrary but should be different from Acme\App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
