post:
    path: /{slug}
    controller: Acme\App\Presentation\Web\Core\Component\Blog\Anonymous\Post\PostController::get
    methods: [GET]
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
