# we need to order the routes
# PostList must come before Post so the rss.xml is not confused with a post ID
anonymous-post_list:
    resource: '../../src/Presentation/Web/Core/Component/Blog/Anonymous/PostList'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

anonymous-post:
    resource: '../../src/Presentation/Web/Core/Component/Blog/Anonymous/Post'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

user:
    resource: '../../src/Presentation/Web/Core/Component/Blog/User'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

admin:
    resource: '../../src/Presentation/Web/Core/Component/Blog/Admin'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

login:
    resource: '../../src/Presentation/Web/Core/Component/Login'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
