Acme\App\Core\Component\Blog\Domain\Post\Comment\Comment:
    type: entity
    table: symfony_demo_comment
    id:
        id:
            type: comment_id
            generator: { strategy: NONE }
    fields:
        content:
            type: text
        publishedAt:
            type: datetime_immutable
    manyToOne:
        post:
            targetEntity: Acme\App\Core\Component\Blog\Domain\Post\Post
            inversedBy: comments
            joinColumn:
                nullable: false
        author:
            targetEntity: Acme\App\Core\Component\User\Domain\User\User
            joinColumn:
                nullable: false
