Acme\App\Core\Component\Blog\Domain\Post\Comment\Comment:
    type: entity
    table: symfony_demo_comment
    id:
        id:
            type: comment_id
            generator: { strategy: NONE }
    fields:
        content:
            type: text
        publishedAt:
            type: datetime_immutable
        authorId:
            type: user_id
            nullable: false
    manyToOne:
        post:
            targetEntity: Acme\App\Core\Component\Blog\Domain\Post\Post
            inversedBy: comments
            joinColumn:
                nullable: false
