Acme\App\Core\Component\Blog\Domain\Post\Tag\Tag:
    type: entity
    table: symfony_demo_tag
    id:
        id:
            type: tag_id
            generator: { strategy: NONE }
    fields:
        name:
            type: string
            unique: true
