parameters:
    # SMS settings
    notification.sms.default_destination: '+19009990006' # Can be a developer phone number, but usually shouldn't
    notification.sms.twilio.client.sid: 'some-dummy-DEV-id'
    notification.sms.twilio.client.token: 'some-dummy-DEV-token'

    # Push settings
    notification.push.one_signal.app_id: 'some-dummy-DEV-id'
    notification.push.one_signal.rest_api_key: 'some-dummy-DEV-key'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # So we can use these fixtures
    Acme\App\Test\Fixture\Doctrine\:
        resource: '../tests/Fixture/Doctrine/*'
